//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoilCare.WebAPI.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Solution
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Solution()
        {
            this.SolutionOffers = new HashSet<SolutionOffer>();
        }
    
        public string Solution_id { get; set; }
        public string Solution_name { get; set; }
        public Nullable<double> Value { get; set; }
        public string Unit_name { get; set; }
        public string Unit_symbol { get; set; }
        public string Solution_purpose { get; set; }
        public string Solution_description { get; set; }
        public string Owner { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SolutionOffer> SolutionOffers { get; set; }
    }
}
